### PR TITLE
Caps updates

### PR DESCRIPTION
**Pull request by bit-pirate**
Various small updates for Kobuki's capabilities (most follow updates added to the rapp platform)

### CODE REVIEW

**Comment by bit-pirate** [comment]
Please sync hydro-devel and indigo after merging this (#329).

**Comment by jihoonl** [comment]
:smile:

**Comment by jihoonl** [comment]
Merged into indigo

https://github.com/yujinrobot/kobuki/commit/d2f29f2b254ba0692aa507b5528394085b6e594c

**Comment by jihoonl** [comment]
Actually it didn't resolve #331. kobuki_node package.xml still depends on kobuki_capabilities and kobuki_capabilities depends on kobuki_node.

**Comment by bit-pirate** [comment]
Sorry, missed that.

**Comment by jihoonl** [comment]
https://github.com/yujinrobot/kobuki/commit/d64f5c5d8e9bdf967b3135f9b854f0666e0baf61 synchronises launcher with current appmanager launcher.

**Pull request merged**
