### PR TITLE
updates kobuki.rosinstall

### LINKED ISSUE #321: [hydro-devel] kobuki.rosinstall refers to incorrect groovy distribution (in the manual notes)
I was using the kobuki.rosinstall files under the hydro-devel branch and the manual notes in the header of that file (for dependencies) refer to the groovy dist.

### PR DESCRIPTION
**Pull request by bit-pirate**
fixes #321 

Remember to cherry-pick this to 'hydro' branch.

### CODE REVIEW

**Comment by stonier** [comment]
Have to forgive his english...he is german ;) @bit-pirate I'll leave the merge and cherry-pick to you and @jihoonl.

**Comment by bit-pirate** [comment]
> Have to forgive his english...he is german ;) 

:punch: 

Fixed the typo and squashed the commits.

**Comment by bit-pirate** [comment]
@jihoonl PR for cherry-picked commit created. Please review and merge. Thx!

**Comment by stonier** [comment]
I got it.

**Pull request merged**
